ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "series" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "rangeStart" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "rangeEnd" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "rangeUnit" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "accuracy" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "accuracyType" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "resolution" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "instrumentId" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "calibrationPoints" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "readingAccuracy" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "calibrationPeriod" TEXT;

ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "invoiceId" INTEGER;

ALTER TABLE "Report" DROP CONSTRAINT IF EXISTS "Report_invoiceId_fkey";
ALTER TABLE "Report"
ADD CONSTRAINT "Report_invoiceId_fkey"
FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
